SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 31
PLAYER_HITBOX_RADIUS = 12
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 100
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 4
SHOT_SPEED = 450
PLAYER_SHOT_COOLDOWN_SECONDS = 0.94
XP_ORB_RADIUS = 6
XP_ORB_PICKUP_RADIUS = 120
XP_ORB_LIFETIME = 10.0
ASTEROID_HITBOX_SCALE = 0.825
INVINCIBILITY_TIME = 2.0

PLAYER_MAX_HP    = 100
PLAYER_REGEN_RATE = 0.5   # HP per second

# Contact damage per hit source
ASTEROID_CONTACT_DAMAGE  = 15
ENEMY_CONTACT_DAMAGE     = 18
CENTIBOMB_CONTACT_DAMAGE = 25
BOSS_CONTACT_DAMAGE      = 35
BOSS_SHOT_DAMAGE         = 20
SHOOTER_SHOT_DAMAGE      = 15

SYPHON_LIFESTEAL_PER_STACK = 0.06   # fraction of damage healed per stack
BACKUP_ENGINE_COOLDOWN_BASE = 120.0  # seconds
BACKUP_ENGINE_COOLDOWN_STEP =  30.0  # reduction per additional stack
BACKUP_ENGINE_HEAL_BASE     =   0.4  # fraction of max HP healed on stack 1
BACKUP_ENGINE_HEAL_STEP     =   0.1  # +fraction per additional stack